config/routes.rb
Ptarmigan::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => 'registrations'}

  themes_for_rails
  resources :attendees do
    collection do
      post :check
    end

  end

  get '/feed', :to => "feed#index"
  get '/archive', :to => "events#archive"
  get '/about', :controller => "pages", :action => "show", :id => "about"
  get '/press', :controller => "pages", :action => "press", :id => "press"
  get "ckeditor/pictures", :via => :post, :controller => 'ckeditor/pictures', :action => :create
  post '/search/simple', :controller => 'application', :action => 'search'
  resources :airforms, :member => {:submit => :get}, :collection => {:submitted => :get}
  get '/aiparty', controller: 'events', action: 'show', id: 'aiparty'
  resources :applicants
  resources :festivals
  resources :places do
    collection do
      post :ctvenues
      get :map_markers
    end

    member do
      post :vote
    end
  end

  resources :podcasts

  resources :proposals do
    collection do
      get :thank_you
      get :axis_of_praxis
    end
  end

  get '/air', :controller => 'pages', :action => 'air'

  get '/admin', :controller => 'admin/reports', :action => :index

  get '/staff', :controller => 'admin/reports', :action => :index
  resources :users
  get '/pages/frontpage', {:controller => :pages, :action => :frontpage}
  get '/pages/:id', {:controller => :pages, :action => :show, :id => :id }

  resources :calendar

  resources :events do
    resources :instances, :path => "performance/"
    resources :attendees
    collection do
      get :archive
      get :archives
    end
  end
  resources :projects do
    collection do
      get :archive
    end
  end
  resources :artists do
    collection do
      get :archive
    end
  end
  resources :pages do
    collection do
      get :frontpage
    end
  end
  resources :posts do
    collection do
      get :witnessed
    end
  end

  resources :institutions

  get '/admin/wiki',  :controller => 'admin/wikipages',  :action => 'show', :title => 'Home page'
  get '/admin/wiki/:title', :controller => 'admin/wikipages',  :action => 'show', :title => :title

  get '/admin/wikipages.:format', :controller => 'admin/wikipages', :action => 'index'
  get '/admin/wikirevisions.:format', :controller => 'admin/wikirevisions', :action => 'index'

  get '/admin/wiki/:title', :controller => 'admin/wikipages', :action => 'show'

  get '/admin/wiki/:title/history', :controller => 'admin/wikipages', :action => 'history', :as => :admin_wikipage_history
  get '/admin/:title/history.:format', :controller => 'admin/wikipages', :action => 'history'

  get '/admin/wiki/:title/edit', :controller => 'admin/wikipages', :action => 'edit'
  get '/territories(/:year(/:month))' => 'pages#frontpage', :as => :ctcalendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get '/madhousebar' => 'events#secondary'
  get '/madbar' => 'events#secondary'
  get '/workshops' => 'events#workshops'
  namespace :admin do
    resources :articles
    resources :calendar
    resources :calendarbackgrounds
    resources :carouselvideos
    resources :ctads
    resources :events do
      resources :instances
    end
    resources :eventcategories
    resources :festivals
    resources :wikirevisions
    resources :wikipages
    resources :documents
    resources :expenses
    resources :subsites
    resources :projects
    resources :podcasts
    resources :pages
    resources :radiolinks
    resources :users
    resources :reports do
      collection do
        post :search
      end
    end
    resources :incomes
    resources :artists
    resources :videohosts
    resources :videos
    resources :flickers do
      member do
        get :remove_carousel
        get :set_carousel
      end
    end
    resources :places
    resources :presslinks
    resources :posts
    resources :airforms
    resources :budgetareas
    resources :wikifiles
    resources :chatters do
      resources :comments
    end

    resources :proposals do
      resources :proposalcomments
    end
    resources :proposalcomments
    resources :resources
    resources :attendees
  end
  post '/add_to_list', :controller => :application, :action => :add_to_mailchimp
  post '/madhouse/add_to_list', controller: :application, action: :madhouse_list_add
  get '/badhouse', to: 'festivals#show', id: 'bad-house'
  root :controller => 'pages', :action => 'frontpage'

end

app/controllers/admin/events_controller.rb
# -*- encoding : utf-8 -*-
class Admin::EventsController < Admin::BaseController

  before_action :find_event
  # before_filter :exclude_guests
  EVENTS_PER_PAGE = 100

  # cache_sweeper :event_sweeper, :only => [ :create, :update , :destroy]


  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        # expire_fragment(@event.location.name + '_projects_page')
        flash[:notice] = 'Event was successfully created.'
        format.html {
            redirect_to admin_events_path
        }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @event.destroy
        flash[:notice] = 'Event was successfully destroyed.'
        format.html { redirect_to admin_events_path }
        format.xml  { head :ok }
      else
        flash[:error] = 'Event could not be destroyed.'
        format.html { redirect_to @event }
        format.xml  { head :unprocessable_entity }
      end
    end
  end

  def edit
    @event = Event.friendly.find(params[:id])
    if @subsite && @subsite.theme == 'creativeterritories'
      @event.location_id = 3
      @event.subsite_id = 5
    end
  end

  def index
    if @subsite
     if @subsite.theme == 'creativeterritories'
        @events = Event.by_subsite(@subsite.id).order('date DESC').page(params[:page])
      else
        @events = Event.page(params[:page]).per(50).order('date DESC')
      end
    else
      if @location.name == 'Mad House'
        @events = Event.by_location(@location.id).page(params[:page]).per(50).order('date DESC')
      else
        @events = Event.page(params[:page]).per(50).order('date DESC')
      end
    end
    respond_to do |format|
      format.html
      format.rss { render :layout => false}
      format.xml  { render :xml => @events }
    end
  end


  def new

    @event = Event.new(:location_id => @subsite.nil? ? @location.try(:id) : @subsite.try(:id), :place_id => nil)
    if @subsite && @subsite.theme == 'creativeterritories'
      @event.location_id = 3
      @event.subsite_id = 5
    end
    respond_to do |format|
      format.html
      format.xml  { render :xml => @event }
    end
  end



  def update
    respond_to do |format|
      if @event.update_attributes(event_params)
        # expire_fragment(@event.location.name + '_projects_page')
        flash[:notice] = 'Event was successfully updated.'
        format.html {
            redirect_to admin_events_path
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    redirect_to edit_admin_event_path(params[:id])
  end
  private

  def find_event
    @event = Event.friendly.find(params[:id]) if params[:id]
  end

  protected

  def event_params
     params.require(:event).permit( [:date, :promoter, :event_type, :cost, :metadata, :notes, :avatar, :public, :enddate,
      :discountedcost, :project_id, :discountreason, :facebook, :registration_required, :registration_limit, :location_id, :is_workshop,
      :place_id, :registration_recipient, :registration_optional_q, :featured, :hide_from_front, :carousel, :remove_carousel,
      :donations_requested, :hide_registrants, :slug, :subsite_id, :show_on_main, :show_guests_to_public, :ticket_url, :teaser, :article_link,
      :require_approval, :redirect_url, :otherweb, :event_time, :secondary, :is_festival, :video_link, :festival_id,
      eventcategory_ids: [], doublebill_ids: [],
      translations_attributes: [:title, :description, :notes, :id, :locale, :_destroy]])
  end


end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
class EventsController < ApplicationController
  respond_to :html, :js
  
  def archive
  #  unless read_fragment({:page => params[:page] || 1})
      @archive = Event.where(['public is true and location_id < 3 and date < ?', Time.now.to_date]).order('date DESC')
      @flickers = Flicker.limit(5).order('rand()')
      @videos = Video.limit(3).order('rand()')
      @projects = Project.by_location(@location.id).order(:name).page params[:page]

    set_meta_tags :open_graph => {
      :title => t(:events),
      :type  => "ptarmigan:event",
      :url   => url_for({:only_path => false, :controller => :events, :action => :archive}),
      }, 
      :canonical => url_for({:only_path => false, :controller => :events, :action => :archive}),
      :keywords => (@location.id == 1 ? 'Helsinki,Finland,' : 'Tallinn,Estonia') + ',Ptarmigan,culture,art,' + @archive[0..40].map{|x| x.event_type }.join(':').split(/\s*\:\s*/).compact.uniq.join(','),
      :description => 'Past events',
      :title => t(:events)
      
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @archive }
    end
  end

  def archives
   #.page(params[:archive_page])
    if @location.id == 4
      @archive = Event.by_location(@location.id).where(['public is true AND date < ?', Time.now.to_date]).order(date: :desc) 
    else
      @archive = Event.by_location(@location.id).where(['public is true AND date < ?', Time.now.to_date]).order(date: :desc).page(params[:archive_page])
      set_meta_tags :open_graph => {
          :title => t(:events) ,
          :type  => "article",
          :url   => url_for({:only_path => false, :controller => :events}),
          }, 
          :canonical => url_for({:only_path => false, :controller => :events}),
          :keywords => (@location.id == 1 ? 'Helsinki,Finland,' : 'Tallinn,Estonia') + ',Ptarmigan,culture,art,' + @archive.map{|x| x.event_type }.join(':').split(/\s*\:\s*/).compact.uniq.join(','),
          :description => 'Past events',
          :title => t(:events)

      respond_to do |format|
        format.html { render  :template => 'events/index' }
        format.rss { render :layout => false}
        format.xml  { render :xml => @archive }
      end
    end
  end

  def index
    if @location.id == 1
      redirect_to projects_path
    else
      if @subsite
        @upcoming = Event.by_subsite(@subsite).by_location(@location.id).where(['public is true AND date >= ?', Time.now.to_date]).order(:date).page params[:page]
      else
        if @location.id == 4
          @upcoming = Event.primary.published.future.by_location(@location.id).order(:date)
          #@upcoming += Event.one_bar.limit(1)
          @upcoming = @upcoming.sort_by(&:next_date)
          #@upcoming = Kaminari.paginate_array(@upcoming).page(params[:page]).per(8)
          
        else
          @upcoming = Event.by_location(@location.id).where(['date >= ?', Time.now.to_date]).order(:date).page(params[:page]).per(8)
        end
      end
      if @upcoming.size < 7 && !@subsite
        @archive = Event.by_location(@location.id).where(['public is true AND date < ?', Time.now.to_date]).order('date DESC').page params[:archive_page]
      else
        @archive = []
      end

      if @location.id == 4

        set_meta_tags :og => {
          :title => "Mad House Helsinki: " + t("madhouse.upcoming_events") ,
          :type  => "article",
          image: 'https://madhousehelsinki.fi/assets/madhouse/images/MADHOUSE_4kausi_coverphoto.jpg',
          :url   => url_for({:only_path => false, :controller => :events}),
          }, 
          :fb  => {
              :app_id => Figaro.env.madhouse_facebook_client_id
            },
          :canonical => url_for({:only_path => false, :controller => :events}),
          :keywords => 'Mad House,Helsinki,Finland,Suvilahti,culture,art,performance,live art' + @upcoming.map{|x| x.name }.join(','),
          :description => t(:upcoming_events),
          :title => "Mad House Helsinki: "  + t(:events) 
      else
        set_meta_tags :og => {
          :title => t(:events) ,
          :type  => "article",
          :url   => url_for({:only_path => false, :controller => :events}),
          }, 
          :canonical => url_for({:only_path => false, :controller => :events}),
          :keywords => ( (@location.id == 1 || @location.id == 4) ? 'Helsinki,Finland,' : 'Tallinn,Estonia') + ',culture,art,Mad House,performance,live art' + @upcoming.map{|x| x.event_type }.join(':').split(/\s*\:\s*/).compact.uniq.join(','),
          :description => t(:upcoming_events),
          :title => t(:events)
      end

      respond_to do |format|
        format.html
        format.js
        format.rss { render :layout => false}
        format.xml  { render :xml => @upcoming }
      end
    end
  end


  def secondary
    @location = Location.find(4)
    @upcoming = Event.by_location(@location).ihana.future.published.order(:date).all
    @ihana = true
    render :template => 'events/index'
  end

  def workshops
    @location = Location.find(4)
    @upcoming = Event.by_location(@location).workshop.future.published.order(:date).all

    render :template => 'events/index'
  end

  def show
    find_event
    unless @event.nil?
      if @event.redirect_url.blank? && @location.id == 4
        set_meta_tags :og => {
          :title =>  @event.title  ,
          :type  => "article",
          locale: {
            _:  session[:locale].to_s + '_' + (session[:locale].to_s == 'sv' ? 'SE' : session[:locale].to_s.upcase)
            
          },

          :url   => url_for(@event),

          :image =>  @event.avatar.url(:medium)
          }, 
          :fb  => {
              :app_id => Figaro.env.madhouse_facebook_client_id
            },
          :canonical => url_for(@event), 
          :keywords => 
          ((@event.location.id == 1 || @event.location.id == 4) ? 'Helsinki,Finland,' : 'Tallinn,Estonia') + 'performance,culture,art, ' + 
          (@event.event_type.blank? ? 'Mad House,live art' : @event.event_type.split(/\:/).each(&:strip).join(',')),
          :description => @event.description,
          :title => @event.title
        if @event.festival
          render layout: @event.festival.slug, template: 'events/' + @event.festival.slug
        else
          render
        end
      elsif @event.location_id == 3  && request.xhr?
        render template: 'events/overlay', layout: false
      elsif request.original_url != @event.redirect_url
        if @subsite || @event.subsite
          redirect_to @event.redirect_url
        end
      end
    end
  end


  private


  def find_event
    if params[:id] =~ /^\d\d\d\d\-\d{1,2}\-\d{1,2}$/
      @events = Event.has_events_on(params[:id])
      @tiib = Cash.tiib_events_on(params[:id])
      @datespan = params[:id]
    else
      @event = Event.friendly.find(params[:id])
      unless @event.flickers.empty?
          require 'flickraw'
      end
      if request.path != event_path(@event) && @event.redirect_url.blank?
        return redirect_to @event, :status => :moved_permanently
      end
    end
  end


end

app/views/admin/events/_form.html.haml
= semantic_form_for([:admin,  event],  :html => {:multipart => true } ) do |f|
  .twelve.columns
    .six.columns.alpha= f.input :location, :label => "Which Ptarmigan?", :as => :select
    .six.columns.omega
      = f.input :subsite, :label => 'Assign to sub-site', :hint => 'will appear in content of subdomain'
      = f.input :show_on_main, :label => 'Also show on main site', :hint => 'Will appear in subdomain but also in main Ptarmigan news on regular site'

  %hr
  .twelve.columns
    .six.columns.clearfix.alpha
      = f.input :date, :as => :string,  :input_html => {:class => 'date-pick'}
      = f.input :enddate, :as => :string, :input_html => {:class => 'date-pick'}, :label => "Ending date", :hint => 'leave blank unless a multi-day event; not for things that will run past midnight'
      = f.input :promoter, :label => "Promoter", :hint => "optional, ex: Äänen Lumo, usually blank though"
    .six.columns.clearfix.omega
      = f.input :place, :as => :select,:collection => Place.for_events.map{|x| [x.name + "/" + x.address1, x.id]}, :hint => "Don't accidentally pick the old Ptarmigan on Nilsiänkatu!", :include_blank => true

      = f.input :event_type, :label => "Event type", :hint => "usually a set of keywords separated by colons, that we haven't set up to link as tags YET"
  .thirteen.columns
    = tabs_for do |tab|
      - tab.create('english', 'English') do
        = f.globalize_fields_for :en do |en|
          %p
            Title
            = en.text_field :title
            Note: you must enter content in all three fields (title, description, notes) for a language
          %p
            Description of event
            = en.cktext_area :description
          %p
            Notes and metadata (start time, etc.)
            %br/
            = en.text_area :notes, {:cols => 40, :rows => 5}
      - tab.create('finnish', 'Finnish') do
        = f.globalize_fields_for :fi do |fi|
          %p
            Title
            = fi.text_field :title
            Note: you must enter content in all three fields (title, description, notes) for a language
          %p
            Tapahtuman kuvaus
            = fi.cktext_area :description
          %p
            Huomautukset ja metatiedot (alkamisaika, jne.)
            %br/
            = fi.text_area :notes, {:cols => 40, :rows => 5}
      - tab.create('estonian', 'Estonian') do
        = f.globalize_fields_for :et do |et|
          %p
            Title
            = et.text_field :title
            Note: you must enter content in all three fields (title, description, notes) for a language
          %p
            Kirjeldus sündmus
            = et.cktext_area :description
          %p
            Märkmed ja metaandmeid (algusaeg, jne)
            %br/
            = et.text_area :notes, {:cols => 40, :rows => 5}
      - tab.create('russian', 'Russian') do
        = f.globalize_fields_for :ru do |ru|
          %p
            Title
            = ru.text_field :title
            Note: you must enter content in all three fields (title, description, notes) for a language
          %p
            Описание мероприятия
            = ru.cktext_area :description
          %p
            Заметки и метаданные (время начала, и т.д.)
            %br/
            = ru.text_area :notes, {:cols => 40, :rows => 5}
      - tab.create('latvian', 'Latvian') do
        = f.globalize_fields_for :lv do |lv|
          %p
            Title
            = lv.text_field :title
            Note: you must enter content in all three fields (title, description, notes) for a language
          %p
            Description of event
            = lv.cktext_area :description
          %p
            Notes and metadata (start time, etc.)
            %br/
            = lv.text_area :notes, {:cols => 40, :rows => 5}
      - tab.create('swedish', 'Swedish') do
        = f.globalize_fields_for :sv do |sv|
          %p
            Title
            = sv.text_field :title
          %p
            Description of event
            = sv.cktext_area :description
          %p
            Notes and metadata (start time, etc.)
            %br/
            = sv.text_area :notes, {:cols => 40, :rows => 5}
  .twelve.columns
    %h4 Other information
    .six.columns.alpha
      = f.input :cost, :label => "Cost", :hint => "enter whatever you want now, it's a free text field"
      = f.input :donations_requested, :label => 'Donations requested?', :hint => "Check this to replace 'FREE' on site with 'Donations requested'"
      = f.input :discountedcost, :label => "Alternate discount cost?", :hint => "this still has to be a number. Just use the cost as a text field now."
      = f.input :discountreason, :label => "Discount reason", :hint => "If discount cost above is enteres, this reason for the discount will be displayed on the lower price, eg: 'With mental alaska membership card'"
    .six.columns.omega
      = f.input :artist, :collection => Artist.order("startdate DESC").map{|x| [x.name[0..40], x.id]}, :hint => "Choose an artist if this event related directly to a resident artist"
      = f.input :project, :collection => Project.order(:location_id, :name).map{|x| ["#{x.name} (#{x.location.name})", x.id]}, :hint => "do NOT choose Tallinn or Helsinki residencies - pick from artist dropdown above if a resident is involved"
      - if f.object.avatar?
        = image_tag f.object.avatar(:thumb)
        = f.check_box :remove_avatar
        Delete image
      = f.input :avatar, :label => "Avatar/image" + (f.object.avatar? ? ' -- change:' : ''), :hint => raw("Image that will appear on event page and listings.  Can be any resolution or aspect ratio. THIS MUST BE JPG OR GIF OR PNG -- <strong><font size='+1'>NO TIFF FILES!!!</font></strong>")
      - if f.object.carousel?
        = image_tag f.object.carousel(:small)
        = f.check_box :remove_carousel
        Delete carousel image
      = f.input :carousel, :label => 'Carousel image' + (f.object.carousel? ?  ' -- change:' : ''), :hint => raw("optional, but recommended.  Must be at least 1180x492, will be cropped if larger. THIS MUST BE JPG OR GIF OR PNG -- <strong><font size='+1'>NO TIFF FILES!!!</font></strong>")
  %hr
  .thirteen.columns
    .six.columns.alpha
      = f.input :facebook, :label =>  'ID of Facebook event (12 digits or so)'
      /= f.input :publicschool, :label => 'ID of Public school class (4 digits or so)'
      = f.input :hide_from_front, :label => 'Hide from frontpage upcoming events listing?'
  
      = f.input :public, :label => 'Publish to site?', :hint => "If unchecked, event will only be seen by staff. Leave unchecked unless you are ready to announce this."
    .six.columns.omega{:style => "border: 1px solid black;"}
      = f.input :registration_required, :label =>  'Registration required?'
      = f.input :registration_limit, :label => 'Maximum participants', :hint => "leave blank for unlimited"
      = f.input :registration_optional_q, :label => 'Optional extra question for reg. form?', :hint => "Add an extra question to the registration form. Unfortunately, only in one language."
      = f.input :registration_recipient, :label => 'Send email after registration to', :hint => 'Defaults to helsinki or tallinn@ptarmigan, but you can have it go to someone else, or multiple addresses separated by commas'
      = f.input :require_approval, :label => "Attendees must be approved by Ptarmigan staff"
      = f.input :hide_registrants, :as => :radio,  :hint => 'Hide the number of places left on the registration form'
      = f.input :show_guests_to_public, :as => :radio,  :hint => 'Show guest list to public through special URL'
      = f.input :redirect_url, :label => 'Redirect to URL', :hint => 'Enter a full URL here (with http://) and the site will redirect to this URL instead of showing the Ptarmigan page. Use for off-site registration form'
  /= f.input :featured, :label => 'Include in forthcoming frontpage events carosel'


  = f.actions do
    = f.submit "Save this event!"

:javascript
  $(function() {
    $("#tabs").tabs();
  });

app/views/admin/events/edit.html.haml
%h3 Editing event / muokkaa tapahtumaa / muuda sündmust
= render :partial => "form", :locals => {:event => @event}
%ul
  %li= link_to 'Show', @event
  %li= link_to 'Back', admin_events_path
  %li= link_to 'Destroy', [:admin, @event], :confirm => 'Are you sure?', :method => :delete  

app/views/admin/events/index.html.haml
%h3 Events

= button_to 'new event', new_admin_event_path, :method => :get
= paginate(@events)


.events
  - @events.each do |event|
    %p
      %span{:class => :smaller_font}= l event.date, :format => :long
      %span{:class => event.location.locale + "_event"}
        = link_to(event.title, edit_admin_event_path(:id => event.id))
        -if event[:public] == false
          %span{:class => 'read_more'}
            %font{:color => 'red'} (Not yet public)
        %span.smaller_font
          = link_to('(edit)', edit_admin_event_path(event))
          %span.delete= link_to('[delete]', admin_event_path(:id => event.id), {:confirm => 'Are you sure?', :method => :delete})

= button_to 'new event', new_admin_event_path, :method => :get
= paginate(@events)

app/views/admin/events/new.html.haml
%h3 New event / uusi tapahtuma / uus sündmuse
= render :partial => "form", :locals => {:event => @event}