config/routes.rb
Ptarmigan::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => 'registrations'}

  themes_for_rails
  resources :attendees do
    collection do
      post :check
    end

  end

  get '/feed', :to => "feed#index"
  get '/archive', :to => "events#archive"
  get '/about', :controller => "pages", :action => "show", :id => "about"
  get '/press', :controller => "pages", :action => "press", :id => "press"
  get "ckeditor/pictures", :via => :post, :controller => 'ckeditor/pictures', :action => :create
  post '/search/simple', :controller => 'application', :action => 'search'
  resources :airforms, :member => {:submit => :get}, :collection => {:submitted => :get}
  get '/aiparty', controller: 'events', action: 'show', id: 'aiparty'
  resources :applicants
  resources :festivals
  resources :places do
    collection do
      post :ctvenues
      get :map_markers
    end

    member do
      post :vote
    end
  end

  resources :podcasts

  resources :proposals do
    collection do
      get :thank_you
      get :axis_of_praxis
    end
  end

  get '/air', :controller => 'pages', :action => 'air'

  get '/admin', :controller => 'admin/reports', :action => :index

  get '/staff', :controller => 'admin/reports', :action => :index
  resources :users
  get '/pages/frontpage', {:controller => :pages, :action => :frontpage}
  get '/pages/:id', {:controller => :pages, :action => :show, :id => :id }

  resources :calendar

  resources :events do
    resources :instances, :path => "performance/"
    resources :attendees
    collection do
      get :archive
      get :archives
    end
  end
  resources :projects do
    collection do
      get :archive
    end
  end
  resources :artists do
    collection do
      get :archive
    end
  end
  resources :pages do
    collection do
      get :frontpage
    end
  end
  resources :posts do
    collection do
      get :witnessed
    end
  end

  resources :institutions

  get '/admin/wiki',  :controller => 'admin/wikipages',  :action => 'show', :title => 'Home page'
  get '/admin/wiki/:title', :controller => 'admin/wikipages',  :action => 'show', :title => :title

  get '/admin/wikipages.:format', :controller => 'admin/wikipages', :action => 'index'
  get '/admin/wikirevisions.:format', :controller => 'admin/wikirevisions', :action => 'index'

  get '/admin/wiki/:title', :controller => 'admin/wikipages', :action => 'show'

  get '/admin/wiki/:title/history', :controller => 'admin/wikipages', :action => 'history', :as => :admin_wikipage_history
  get '/admin/:title/history.:format', :controller => 'admin/wikipages', :action => 'history'

  get '/admin/wiki/:title/edit', :controller => 'admin/wikipages', :action => 'edit'
  get '/territories(/:year(/:month))' => 'pages#frontpage', :as => :ctcalendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get '/madhousebar' => 'events#secondary'
  get '/madbar' => 'events#secondary'
  get '/workshops' => 'events#workshops'
  namespace :admin do
    resources :articles
    resources :calendar
    resources :calendarbackgrounds
    resources :carouselvideos
    resources :ctads
    resources :events do
      resources :instances
    end
    resources :eventcategories
    resources :festivals
    resources :wikirevisions
    resources :wikipages
    resources :documents
    resources :expenses
    resources :subsites
    resources :projects
    resources :podcasts
    resources :pages
    resources :radiolinks
    resources :users
    resources :reports do
      collection do
        post :search
      end
    end
    resources :incomes
    resources :artists
    resources :videohosts
    resources :videos
    resources :flickers do
      member do
        get :remove_carousel
        get :set_carousel
      end
    end
    resources :places
    resources :presslinks
    resources :posts
    resources :airforms
    resources :budgetareas
    resources :wikifiles
    resources :chatters do
      resources :comments
    end

    resources :proposals do
      resources :proposalcomments
    end
    resources :proposalcomments
    resources :resources
    resources :attendees
  end
  post '/add_to_list', :controller => :application, :action => :add_to_mailchimp
  post '/madhouse/add_to_list', controller: :application, action: :madhouse_list_add
  get '/badhouse', to: 'festivals#show', id: 'bad-house'
  root :controller => 'pages', :action => 'frontpage'

end

app/models/income.rb
# -*- encoding : utf-8 -*-
class Income < ActiveRecord::Base
  belongs_to :event
  has_many :wikifiles, :dependent => :destroy, :as => :wikiattachment
  accepts_nested_attributes_for :wikifiles, :allow_destroy => true #, :reject_if => proc { |t| t['attachment'].blank?  }
  belongs_to :location
  belongs_to :budgetarea
  validates_presence_of :location_id, :amount, :when, :source, :what_for
      
  # scope :by_location
  # scope :by_recipient
  # scope :by_month
  # scope :by_payer
  # scope :by_budgetarea
  scope :i_location, -> (location) { where(location_id: location)}
  scope :i_month, -> (month) { where(["incomes.when >= ? AND incomes.when <= ?", 
      Date.new(*(Date.parse(month).strftime('%Y %m') + " 1").split.map{|x| x.to_i }),
     Date.new(*(Date.parse(month).strftime('%Y %m') + " -1").split.map{|x| x.to_i })])}

  scope :by_year, ->(year) {where(["incomes.when >= ? AND incomes.when <= ?", 
    Date.parse(year + "-01-01").to_s,
    Date.parse(year + "-12-31").to_s])}

  scope :i_budgetarea,->(budgetarea) { where(budgetarea_id: budgetarea)}
  scope :i_event, ->(event) { where(event_id: event)}
  scope :i_source, ->(payer) { where(source: payer)}

 
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller.current_user }
      
  def name
    income_name
  end
  
  def income_name
    what_for + " / " + source + " [#{self.when.strftime('%d %B %Y')}]"
  end

  def icon
    'income_icon.png' 
  end  
end

app/controllers/admin/incomes_controller.rb
# -*- encoding : utf-8 -*-
class Admin::IncomesController < Admin::BaseController
  before_action :authenticate_user!
  before_action :exclude_guests  

  layout 'staff'
  load_and_authorize_resource
  def create
    create! { admin_expenses_path }
  end

  def index
    if params[:render_csv] == "1"
      @expenses = Expense.order('expenses.when DESC')
      @incomes = Income.order('incomes.when DESC')
      render_csv("incomes", "incomes")
    else
      @expenses = apply_scopes(Expense).order('expenses.when DESC').page(params[:page]).per(100)
      @incomes = apply_scopes(Income).order('incomes.when DESC').page(params[:page]).per(100)
    end
  end  
  
  def update
    update! { admin_expenses_path }
  end
  
  protected

  def render_csv(filename = nil, template = nil)
    require 'csv'
    filename ||= params[:action]
    filename += '.csv'

    if request.env['HTTP_USER_AGENT'] =~ /msie/i
      headers['Pragma'] = 'public'
      headers["Content-type"] = "text/plain" 
      headers['Cache-Control'] = 'no-cache, must-revalidate, post-check=0, pre-check=0'
      headers['Content-Disposition'] = "attachment; filename=\"#{filename}\"" 
      headers['Expires'] = "0" 
    else
      headers["Content-Type"] ||= 'text/csv'
      headers["Content-Disposition"] = "attachment; filename=\"#{filename}\"" 
    end
    render :layout => false, :file => "#{Rails.root}/app/views/admin/incomes/#{template}.csv.erb"
  end
  
  
end

app/views/admin/incomes/_form.html.haml
= semantic_nested_form_for([:admin, @income], :html => {:multipart => true}) do |f|
  = f.input :location
  %hr
  .six.columns
    = f.input :when, :as => :string, :input_html => {:class => 'date-pick' }
    = f.input :what_for
    %label For event (optional):
    = f.collection_select :event_id, Event.order('date DESC'), :id, :longer_title, :include_blank => true
  .six.columns
    = f.input :amount
    = f.input :source, :label => "Source of income?", :hint => "(examples, KK Nord, Arts council, etc.)" 
    = f.input :budgetarea, :label => "Budget area (optional)"
    = f.input :has_receipt, :label => "Do we have a receipt?"
  .thirteen.columns
    = f.semantic_fields_for :wikifiles do |ff|
      - unless ff.object.new_record?
        - unless ff.object.attachment_file_name.blank?
          %p= link_to '[download: ' +  ff.object.attachment_file_name  + "]", ff.object.attachment.url
      = ff.input :attachment, :label => (ff.object.new_record? ? 'Attach file' : 'Replace attachment')
      = ff.input :documenttype, :as => :select, :label => "Type of document"      
      = ff.input :description, :as => :string, :label => "Description of this attachment, ex. 'the invoice'"
      = ff.link_to_remove "Remove this attachment"
    = f.link_to_add 'Add an attachment (PDF or other file for invoice, receipt)', :wikifiles
  %p
    = f.label :hidden
    %br
    = f.check_box :hidden
  %p
    = f.submit "Submit"

app/views/admin/incomes/_income.html.haml
%div[income]
  %tbody
    %tr
      %td
        =h income.date
      %td
        =h income.name
      %td
        =h income.income_type
      %td
        =h event_name(income.event)
      %td
        =h income.amount
      %td
        = link_to 'Show', admin_incomes_path(:id => income)
        = link_to 'Edit', edit_admin_income_path(income)
        = link_to 'Destroy', [:admin, income], :confirm => 'Are you sure?', :method => :delete

app/views/admin/incomes/edit.html.haml
%h2 Editing income
= render :partial => "form", :locals => {:income => @income}
%ul
  %li= link_to 'Show', [:admin, @income]
  %li= link_to 'Back', admin_incomes_path
  %li= link_to 'Destroy',  [:admin, @income], :confirm => 'Are you sure?', :method => :delete  

app/views/admin/incomes/incomes.csv.erb
When,Where,Source,What for,Event or budget area,Receipt,Amount
<%= CSV.generate do |csv|
   @incomes.each do |cs|
     csv << [ cs.when.strftime('%d/%m/%Y'), cs.location.name,  cs.source, cs.what_for,
        (cs.event.nil? ? "" : cs.event.name + " - ") + (cs.budgetarea.blank? ? "" :  cs.budgetarea.name),
        cs.has_receipt, 
          sprintf("%.2f", cs.amount)
        ]
    end
    csv << [ 'Totals', nil, nil, nil, nil, nil, 
          sprintf("%.2f", @expenses.map(&:amount).flatten.sum)
        ]
end %>

app/views/admin/incomes/index.html.haml
%h2 Listing incomes
- if !@incomes.empty?
  .incomes
    %table{:cellpadding => 5, :cellspacing => 5, :border => 0}
      = render :partial => "income", :collection => @incomes
  = will_paginate(@incomes)
- else
  %p There are no incomes to show yet.
= link_to 'New income', new_admin_income_path
%br
= link_to 'Back to admin home', admin_reports_path

app/views/admin/incomes/new.html.haml
%h3 New income
= render :partial => "form", :locals => {:income => @income}

app/views/admin/incomes/show.html.haml
%h2= "Income \"#{@income.to_param}\""
%div[@income]
  %ul
    %li
      %strong Date:
      =h @income.date
    %li
      %strong Name:
      =h @income.name
    %li
      %strong Income type:
      =h @income.income_type
    %li
      %strong Event:
      =h @income.event_id
    %li
      %strong Amount:
      =h @income.amount
    %li
      %strong Hidden:
      =h @income.hidden
%ul
  %li= link_to 'Edit', edit_income_path(@income)
  %li= link_to 'Back', incomes_path