config/routes.rb
Ptarmigan::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => 'registrations'}

  themes_for_rails
  resources :attendees do
    collection do
      post :check
    end

  end

  get '/feed', :to => "feed#index"
  get '/archive', :to => "events#archive"
  get '/about', :controller => "pages", :action => "show", :id => "about"
  get '/press', :controller => "pages", :action => "press", :id => "press"
  get "ckeditor/pictures", :via => :post, :controller => 'ckeditor/pictures', :action => :create
  post '/search/simple', :controller => 'application', :action => 'search'
  resources :airforms, :member => {:submit => :get}, :collection => {:submitted => :get}
  get '/aiparty', controller: 'events', action: 'show', id: 'aiparty'
  resources :applicants
  resources :festivals
  resources :places do
    collection do
      post :ctvenues
      get :map_markers
    end

    member do
      post :vote
    end
  end

  resources :podcasts

  resources :proposals do
    collection do
      get :thank_you
      get :axis_of_praxis
    end
  end

  get '/air', :controller => 'pages', :action => 'air'

  get '/admin', :controller => 'admin/reports', :action => :index

  get '/staff', :controller => 'admin/reports', :action => :index
  resources :users
  get '/pages/frontpage', {:controller => :pages, :action => :frontpage}
  get '/pages/:id', {:controller => :pages, :action => :show, :id => :id }

  resources :calendar

  resources :events do
    resources :instances, :path => "performance/"
    resources :attendees
    collection do
      get :archive
      get :archives
    end
  end
  resources :projects do
    collection do
      get :archive
    end
  end
  resources :artists do
    collection do
      get :archive
    end
  end
  resources :pages do
    collection do
      get :frontpage
    end
  end
  resources :posts do
    collection do
      get :witnessed
    end
  end

  resources :institutions

  get '/admin/wiki',  :controller => 'admin/wikipages',  :action => 'show', :title => 'Home page'
  get '/admin/wiki/:title', :controller => 'admin/wikipages',  :action => 'show', :title => :title

  get '/admin/wikipages.:format', :controller => 'admin/wikipages', :action => 'index'
  get '/admin/wikirevisions.:format', :controller => 'admin/wikirevisions', :action => 'index'

  get '/admin/wiki/:title', :controller => 'admin/wikipages', :action => 'show'

  get '/admin/wiki/:title/history', :controller => 'admin/wikipages', :action => 'history', :as => :admin_wikipage_history
  get '/admin/:title/history.:format', :controller => 'admin/wikipages', :action => 'history'

  get '/admin/wiki/:title/edit', :controller => 'admin/wikipages', :action => 'edit'
  get '/territories(/:year(/:month))' => 'pages#frontpage', :as => :ctcalendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get '/madhousebar' => 'events#secondary'
  get '/madbar' => 'events#secondary'
  get '/workshops' => 'events#workshops'
  namespace :admin do
    resources :articles
    resources :calendar
    resources :calendarbackgrounds
    resources :carouselvideos
    resources :ctads
    resources :events do
      resources :instances
    end
    resources :eventcategories
    resources :festivals
    resources :wikirevisions
    resources :wikipages
    resources :documents
    resources :expenses
    resources :subsites
    resources :projects
    resources :podcasts
    resources :pages
    resources :radiolinks
    resources :users
    resources :reports do
      collection do
        post :search
      end
    end
    resources :incomes
    resources :artists
    resources :videohosts
    resources :videos
    resources :flickers do
      member do
        get :remove_carousel
        get :set_carousel
      end
    end
    resources :places
    resources :presslinks
    resources :posts
    resources :airforms
    resources :budgetareas
    resources :wikifiles
    resources :chatters do
      resources :comments
    end

    resources :proposals do
      resources :proposalcomments
    end
    resources :proposalcomments
    resources :resources
    resources :attendees
  end
  post '/add_to_list', :controller => :application, :action => :add_to_mailchimp
  post '/madhouse/add_to_list', controller: :application, action: :madhouse_list_add
  get '/badhouse', to: 'festivals#show', id: 'bad-house'
  root :controller => 'pages', :action => 'frontpage'

end

app/views/themes/kimmomodig/layouts/application.html.haml
!!! 5
%html
  %head
    = display_meta_tags :site => "Kimmo Modig: Cool stories | Ptarmigan", :og => {:url => 'http://kimmomodig.ptarmigan.ee', :title => 'Kimmo Modig: Tallinn stories'}
    %meta{ :"http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
    %link{ :rel => "shortcut icon", :href => "/favicon.ico" }
    %link{ :rel => "alternate", :type => "application/rss+xml", :title => "Ptarmigan RSS", :href => "/feed.rss"}
    = stylesheet_link_tag :application
    = stylesheet_link_tag 'kimmomodig/stylesheets/application', :media => :screen
    = javascript_include_tag :application
    = javascript_include_tag theme_javascript_path(:application)
    = csrf_meta_tag

    %script{:type => "text/javascript", :src => "http://w.sharethis.com/button/buttons.js"}
    %script{:type => "text/javascript"} stLight.options({publisher: "ur-dae0667d-47dc-d390-f0b1-129d17517bbe"});
    %script{:type => "text/javascript"}
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-12518395-2']);
      _gaq.push(['_trackPageview']);

      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
      var switchTo5x=true;
    %script{:type => "text/javascript", :src => "http://w.sharethis.com/button/buttons.js"}
    %script{:type => "text/javascript"} stLight.options({publisher: "ur-dae0667d-47dc-d390-f0b1-129d17517bbe"});
    

    %meta{ :content => "1 day", :name => "revisit-after" }

  %body
    #fb-root
    :javascript
      (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=1472879426262623&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    .container
      %header
        .sixteen.columns.alpha
          %h1= link_to  "Kimmo Modig: Cool stories", '/'

        .sixteen.columns.alpha
          %p Each one of these texts have been written in an hour. I haven't edited them after writing. This is how I express myself in 2014.
          
    .container
      .thirteen.columns.alpha= yield

      
      %aside
        .sidebar.three.columns.omega
          %p
            Kimmo Modig was artist-in-residence at Ptarmigan during May 2014. The
            = link_to "Axis of Praxis", project_path('eesti-axis-of-praxis')
            residency, in conjunction with 
            = link_to 'MoKS,', 'http://moks.ee'
            was supported by
            = link_to 'Kulturkontakt Nord.', 'http://kulturkontaktnord.org'
          %ul
            %li= link_to 'Kimmo Modig website', 'http://kimmomodig.com'
            %li= link_to 'Ptarmigan website', 'http://ptarmigan.ee'
            
    .container
      %footer
        .ptarmigan_footer
          MTÜ Ptarmigan | Toom-Kooli 13
          | 10130 Tallinn, Estonia 
          |
          = link_to 'GitHub', 'https://github.com/cenotaph/ptarmigan' 
:javascript
  $(document).ready(function() {
    #{yield :jquery}
  });    