config/routes.rb
Ptarmigan::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => 'registrations'}

  themes_for_rails
  resources :attendees do
    collection do
      post :check
    end

  end

  get '/feed', :to => "feed#index"
  get '/archive', :to => "events#archive"
  get '/about', :controller => "pages", :action => "show", :id => "about"
  get '/press', :controller => "pages", :action => "press", :id => "press"
  get "ckeditor/pictures", :via => :post, :controller => 'ckeditor/pictures', :action => :create
  post '/search/simple', :controller => 'application', :action => 'search'
  resources :airforms, :member => {:submit => :get}, :collection => {:submitted => :get}
  get '/aiparty', controller: 'events', action: 'show', id: 'aiparty'
  resources :applicants
  resources :festivals
  resources :places do
    collection do
      post :ctvenues
      get :map_markers
    end

    member do
      post :vote
    end
  end

  resources :podcasts

  resources :proposals do
    collection do
      get :thank_you
      get :axis_of_praxis
    end
  end

  get '/air', :controller => 'pages', :action => 'air'

  get '/admin', :controller => 'admin/reports', :action => :index

  get '/staff', :controller => 'admin/reports', :action => :index
  resources :users
  get '/pages/frontpage', {:controller => :pages, :action => :frontpage}
  get '/pages/:id', {:controller => :pages, :action => :show, :id => :id }

  resources :calendar

  resources :events do
    resources :instances, :path => "performance/"
    resources :attendees
    collection do
      get :archive
      get :archives
    end
  end
  resources :projects do
    collection do
      get :archive
    end
  end
  resources :artists do
    collection do
      get :archive
    end
  end
  resources :pages do
    collection do
      get :frontpage
    end
  end
  resources :posts do
    collection do
      get :witnessed
    end
  end

  resources :institutions

  get '/admin/wiki',  :controller => 'admin/wikipages',  :action => 'show', :title => 'Home page'
  get '/admin/wiki/:title', :controller => 'admin/wikipages',  :action => 'show', :title => :title

  get '/admin/wikipages.:format', :controller => 'admin/wikipages', :action => 'index'
  get '/admin/wikirevisions.:format', :controller => 'admin/wikirevisions', :action => 'index'

  get '/admin/wiki/:title', :controller => 'admin/wikipages', :action => 'show'

  get '/admin/wiki/:title/history', :controller => 'admin/wikipages', :action => 'history', :as => :admin_wikipage_history
  get '/admin/:title/history.:format', :controller => 'admin/wikipages', :action => 'history'

  get '/admin/wiki/:title/edit', :controller => 'admin/wikipages', :action => 'edit'
  get '/territories(/:year(/:month))' => 'pages#frontpage', :as => :ctcalendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get '/madhousebar' => 'events#secondary'
  get '/madbar' => 'events#secondary'
  get '/workshops' => 'events#workshops'
  namespace :admin do
    resources :articles
    resources :calendar
    resources :calendarbackgrounds
    resources :carouselvideos
    resources :ctads
    resources :events do
      resources :instances
    end
    resources :eventcategories
    resources :festivals
    resources :wikirevisions
    resources :wikipages
    resources :documents
    resources :expenses
    resources :subsites
    resources :projects
    resources :podcasts
    resources :pages
    resources :radiolinks
    resources :users
    resources :reports do
      collection do
        post :search
      end
    end
    resources :incomes
    resources :artists
    resources :videohosts
    resources :videos
    resources :flickers do
      member do
        get :remove_carousel
        get :set_carousel
      end
    end
    resources :places
    resources :presslinks
    resources :posts
    resources :airforms
    resources :budgetareas
    resources :wikifiles
    resources :chatters do
      resources :comments
    end

    resources :proposals do
      resources :proposalcomments
    end
    resources :proposalcomments
    resources :resources
    resources :attendees
  end
  post '/add_to_list', :controller => :application, :action => :add_to_mailchimp
  post '/madhouse/add_to_list', controller: :application, action: :madhouse_list_add
  get '/badhouse', to: 'festivals#show', id: 'bad-house'
  root :controller => 'pages', :action => 'frontpage'

end

app/models/wikirevision.rb
# -*- encoding : utf-8 -*-
class Wikirevision < ActiveRecord::Base
  belongs_to :user
  belongs_to :wikipage
  attr_accessor :menuize
  has_many :wikifiles, :dependent => :destroy, :as => :wikiattachment
  accepts_nested_attributes_for :wikifiles, :allow_destroy => true, :reject_if => proc { |t| t['attachment'].blank? || !t['id'].blank? }
  
  after_save :set_menuize
  
  def set_menuize
    wikipage.menuize = self.menuize
    wikipage.save!
  end
  
  def contents_linked
    if self.parsed_contents =~ /\<table/
      self.parsed_contents.gsub(/\[\[([\w\-\s]*)\]\]/, '<a href="/admin/wiki/\1">\1</a>').gsub(/(.*)\r\n\r\n/, '<p>\1</p>')
    else
      self.parsed_contents.gsub(/\[\[([\w\-\s]*)\]\]/, '<a href="/admin/wiki/\1">\1</a>') #.gsub(/(.*)\r\n\r\n/, '<p>\1</p>')
    end
  end
    

  def parsed_contents
    contents = self.contents.gsub(/\n{2,}/, "<br /><br />").gsub(/(\w*_\w*)/) {|match| "<a href='#{match.downcase}'>#{match.gsub('_', ' ')}</a>"}
  end

  def name
    wikipage.title
  end


end

app/controllers/admin/wikirevisions_controller.rb
# -*- encoding : utf-8 -*-
class Admin::WikirevisionsController < Admin::BaseController
  layout 'staff'
  before_action :load_resource, :only => [:show, :edit, :update, :destroy]
  before_action :load_and_paginate_resources, :only => [:index]
  before_action :authenticate_user!
  load_and_authorize_resource
  
  # GET /wikirevisions
  # GET /wikirevisions.js
  # GET /wikirevisions.xml
  # GET /wikirevisions.json
  def index
    respond_to do |format|
      format.html # index.html.haml
      format.js   # index.js.rjs
      format.xml  { render :xml => @wikirevisions }
      format.json  { render :json => @wikirevisions }
    end
  end
  
  # GET /wikirevisions/:id
  # GET /wikirevisions/:id.js
  # GET /wikirevisions/:id.xml
  # GET /wikirevisions/:id.json
  def show
    respond_to do |format|
      format.html # show.html.haml
      format.js   # show.js.rjs
      format.xml  { render :xml => @wikirevisions }
      format.json  { render :json => @wikirevisions }
    end
  end
  
  # GET /wikirevisions/new
  # GET /wikirevisions/new.js
  # GET /wikirevisions/new.xml
  # GET /wikirevisions/new.json
  def new
    @wikirevision = Wikirevision.new
    # @wikirevision.wikifiles << Wikifile.new
    respond_to do |format|
      format.html # new.html.haml
      format.js   # new.js.rjs
      format.xml  { render :xml => @wikirevision }
      format.json  { render :json => @wikirevision }
    end
  end
  
  # GET /wikirevisions/:id/edit
  def edit
    @wikipage = Wikipage.find_by_title(params[:title])
  end
  
  # POST /wikirevisions
  # POST /wikirevisions.js
  # POST /wikirevisions.xml
  # POST /wikirevisions.json
  def create
    pa = params[:wikirevision]

    watts = pa[:wikifiles_attributes] if params[:wikirevision][:wikifiles_attributes]
    pa.delete :wikifiles_attributes

    @wikirevision = Wikirevision.new(pa) 
    respond_to do |format|
      if @wikirevision.save
        if watts
          watts.each do |wa|
            if wa.last['id']
              wf = Wikifile.find(wa.last['id'])
              if wa.last['_destroy'] == "1"
                wf.destroy
              else
                @wikirevision.wikifiles << wf
                wf.save!
              end
            elsif wa.last['attachment']

              # wa.last[:wikirevision_id] = @wikirevision.id

              wf = Wikifile.new(wa.last)
              wf.save!
              @wikirevision.wikifiles << wf
              @wikirevision.save!
            end
          end

        else
          logger.warn('no dice' + params[:wikirevision].inspect)
        end
        flash[:notice] = "Wikirevision was successfully created."
        format.html { redirect_to '/admin/wiki/' + @wikirevision.wikipage.title.gsub(/\s/, '_') }
        format.js   # create.js.rjs
        format.xml  { render :xml => @wikirevision, :status => :created, :location => @wikirevision }
        format.json  { render :json => @wikirevision, :status => :created, :location => @wikirevision }
      else
        flash[:error] = "Wikirevision could not be created."
        @wikipage = @wikirevision.wikipage
        format.html { render :template => 'admin/wikipages/edit'}
        format.js   # create.js.rjs
        format.xml  { render :xml => @wikirevision.errors, :status => :unprocessable_entity }
        format.json  { render :json => @wikirevision.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /wikirevisions/:id
  # PUT /wikirevisions/:id.js
  # PUT /wikirevisions/:id.xml
  # PUT /wikirevisions/:id.json
  def update
  create
  end
  
  # DELETE /wikirevisions/:id
  # DELETE /wikirevisions/:id.js
  # DELETE /wikirevisions/:id.xml
  # DELETE /wikirevisions/:id.json
  def destroy
    respond_to do |format|
      if @wikirevision.destroy
        flash[:notice] = "Wikirevision was successfully destroyed."
        format.html { redirect_to(wikirevisions_url) }
        format.js   # destroy.js.rjs
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        flash[:error] = "Wikirevision could not be destroyed."
        format.html { redirect_to(wikirevision_url(@wikirevision)) }
        format.js   # destroy.js.rjs
        format.xml  { head :unprocessable_entity }
        format.json  { head :unprocessable_entity }
      end
    end
  end
  
  protected
    
    def collection
      paginate_options ||= {}
      paginate_options[:page] ||= (params[:page] || 1)
      paginate_options[:per_page] ||= (params[:per_page] || 20)
      @collection = @wikirevisions ||= Wikirevision.page(params[:page]).per(20)
    end
    alias :load_and_paginate_resources :collection
    
    def resource
      @resource = @wikirevision ||= Wikirevision.find(params[:id])
    end
    alias :load_resource :resource
    
end

app/views/admin/wikirevisions/_form.html.haml
= form.inputs do
  = form.input :user_id,  :as => :hidden, :input_html => { :value => current_user.id }
  = form.input :contents, :label => 'Contents'
  = form.input :wikipage_id, :as => :hidden, :input_html => { :value => @wikipage.id }
  / /- @wikipage.wikifiles.build if @wikipage.wikifiles.empty?
  / = form.semantic_fields_for :wikifiles do |ff|
  /   - unless ff.object.new_record?
  /     - unless ff.object.attachment_file_name.blank?
  /       %p= ff.object.attachment_file_name
  /   = ff.input :attachment, :label => (ff.object.new_record? ? 'Attach file' : 'Change attachment')
  /   = ff.input :description, :as => :string, :label => "Description of this attachment, ex. 'the invoice'"
  /   = ff.link_to_remove "Remove this attachment"
  / = form.link_to_add 'Add an attachment (PDF or other file for invoice, receipt)', :wikifiles
    
  #wikifiles
    - @wikirevision.wikifiles.build if @wikirevision.wikifiles.empty?
    = form.semantic_fields_for :wikifiles do |ff|
      .wiki_attachment= render :partial => 'admin/wikirevisions/wikifile_fields', :locals => { :ff => ff }
  .add_link= link_to_add_fields "+ Add another attachment", form, :wikifiles
  = form.input :menuize, :as => :boolean, :label => 'Put link to this page on main staff menu', :input_html => {:checked => @wikirevision.wikipage.nil? ? false : @wikirevision.wikipage.menuize}

app/views/admin/wikirevisions/_item.html.haml
%tr[wikirevision]{class: cycle('odd', 'even')}
  %td.user= h wikirevision.try(:user).login
  %td.contents= h wikirevision.try(:contents)
  %td.page= h wikirevision.try(:wikipage).title
  %td.actions
    = link_to 'Show', wikirevision_path(wikirevision)
    |
    = link_to 'Edit', edit_wikirevision_path(wikirevision)
    |
    = link_to 'Destroy', wikirevision, :confirm => 'Are you sure?', :method => :delete

app/views/admin/wikirevisions/_new.html.haml
%h1.heading
  - if @wikirevision.new_record?
    = 'This page did not previously exist'
  
%p 
  You can edit this page using the Textile markup language (or plain text).
  = link_to 'Textile reference', 'http://redcloth.org/textile/writing-paragraph-text/', :target => :_blank
  
= semantic_nested_form_for([:admin, @wikirevision], :html => {:multipart => true}) do |form|
  = render 'admin/wikirevisions/form', :form => form
  = form.actions do
    = form.submit 'Save'
    
%p.actions
  = link_to 'Cancel', admin_wikirevisions_path

app/views/admin/wikirevisions/_wikifile_fields.html.haml
.new_wikifile
  Add one or more attachments:
  %div
    - unless ff.object.new_record? || !ff.object.attachment?
      - if ["image/jpeg", "image/gif", "image/png", "image/jpg", "image/pjpeg"].include?(ff.object.attachment_content_type)
        = image_tag ff.object.attachment.url
      = link_to ff.object.attachment_file_name + " (#{ff.object.attachment_file_size} bytes)", ff.object.attachment.url
      = ff.input '_destroy', :as => :boolean, :label => 'delete this attachment'
    = ff.input :documenttype, :label => "Type of attachment"
    = ff.input :description, :label => "Name/description", :as => :string
    = ff.input :attachment, :label => (ff.object.new_record? ? 'Upload attachment:' : 'Change attachment:')

app/views/admin/wikirevisions/edit.html.haml
%h1.heading
  = "Editing wikirevision %s" % @wikirevision.id
  
= semantic_nested_form_for(@wikirevision, :html => {:multipart => true}) do |form|
  = render 'form', :form => form
  = form.actions do
    = form.submit 'Update'
    

app/views/admin/wikirevisions/index.html.haml
%h1.heading
  = "Wikirevisions"
  
%p.actions
  = link_to 'New Wikirevision', new_wikirevision_path
  
%table
  %thead.header
    %tr
      %th.user= 'User'
      %th.contents= 'Contents'
      %th.page= 'Page'
      %th.actions= 'Actions'
  %tbody.items.wikirevisions
    - @wikirevisions.each do |wikirevision|
      = render 'item', :wikirevision => wikirevision
      
= will_paginate(@wikirevisions)

app/views/admin/wikirevisions/show.html.haml
%h1.heading
  = "Wikirevision %s" % @wikirevision.id
  
%dl[@wikirevision]
  %dt.label= 'User'
  %dd.user= h @wikirevision.try(:user)
  %dt.label= 'Contents'
  %dd.contents= h @wikirevision.try(:contents)
  %dt.label= 'Page'
  %dd.page= h @wikirevision.try(:wikipage)
  
%p.actions
  = link_to 'Edit', edit_admin_wikirevision_path(@wikirevision)
  |
  = link_to 'Index', admin_wikipages_path